;; ==========================================================
;; Class accessors
;; Bigloo (4.7a)
;; Inria -- Sophia Antipolis     Thu Mar 6 07:34:14 AM CET 2025 
;; (bigloo -classgen Ast/node.scm)
;; ==========================================================

;; The directives
(directives
   (include "Ast/var.sch"
	    "Type/type.sch"
	    "Object/class.sch")
   (import type_type
	   object_class
	   object_slots
	   ast_var
	   ast_node)
;; node
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-node::node loc1580::obj type1581::type)
    (inline node?::bool ::obj)
    (node-nil::node)
    (inline node-type::type ::node)
    (inline node-type-set! ::node ::type)
    (inline node-loc::obj ::node))))

;; node/effect
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-node/effect::node/effect loc1575::obj type1576::type side-effect?1577::obj key1578::obj)
    (inline node/effect?::bool ::obj)
    (node/effect-nil::node/effect)
    (inline node/effect-key::obj ::node/effect)
    (inline node/effect-key-set! ::node/effect ::obj)
    (inline node/effect-side-effect?::obj ::node/effect)
    (inline node/effect-side-effect?-set! ::node/effect ::obj)
    (inline node/effect-type::type ::node/effect)
    (inline node/effect-type-set! ::node/effect ::type)
    (inline node/effect-loc::obj ::node/effect))))

;; atom
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-atom::atom loc1571::obj type1572::type value1573::obj)
    (inline atom?::bool ::obj)
    (atom-nil::atom)
    (inline atom-value::obj ::atom)
    (inline atom-value-set! ::atom ::obj)
    (inline atom-type::type ::atom)
    (inline atom-type-set! ::atom ::type)
    (inline atom-loc::obj ::atom))))

;; var
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-var::var loc1567::obj type1568::type variable1569::variable)
    (inline var?::bool ::obj)
    (var-nil::var)
    (inline var-variable::variable ::var)
    (inline var-variable-set! ::var ::variable)
    (inline var-type::type ::var)
    (inline var-type-set! ::var ::type)
    (inline var-loc::obj ::var))))

;; closure
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-closure::closure loc1563::obj type1564::type variable1565::variable)
    (inline closure?::bool ::obj)
    (closure-nil::closure)
    (inline closure-variable::variable ::closure)
    (inline closure-variable-set! ::closure ::variable)
    (inline closure-type::type ::closure)
    (inline closure-type-set! ::closure ::type)
    (inline closure-loc::obj ::closure))))

;; kwote
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-kwote::kwote loc1559::obj type1560::type value1561::obj)
    (inline kwote?::bool ::obj)
    (kwote-nil::kwote)
    (inline kwote-value::obj ::kwote)
    (inline kwote-type::type ::kwote)
    (inline kwote-type-set! ::kwote ::type)
    (inline kwote-loc::obj ::kwote))))

;; sequence
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-sequence::sequence loc1553::obj type1554::type side-effect?1555::obj key1556::obj nodes1557::obj)
    (inline sequence?::bool ::obj)
    (sequence-nil::sequence)
    (inline sequence-nodes::obj ::sequence)
    (inline sequence-key::obj ::sequence)
    (inline sequence-key-set! ::sequence ::obj)
    (inline sequence-side-effect?::obj ::sequence)
    (inline sequence-side-effect?-set! ::sequence ::obj)
    (inline sequence-type::type ::sequence)
    (inline sequence-type-set! ::sequence ::type)
    (inline sequence-loc::obj ::sequence))))

;; app
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-app::app loc1546::obj type1547::type side-effect?1548::obj key1549::obj fun1550::var args1551::obj)
    (inline app?::bool ::obj)
    (app-nil::app)
    (inline app-args::obj ::app)
    (inline app-args-set! ::app ::obj)
    (inline app-fun::var ::app)
    (inline app-fun-set! ::app ::var)
    (inline app-key::obj ::app)
    (inline app-key-set! ::app ::obj)
    (inline app-side-effect?::obj ::app)
    (inline app-side-effect?-set! ::app ::obj)
    (inline app-type::type ::app)
    (inline app-type-set! ::app ::type)
    (inline app-loc::obj ::app))))

;; app-ly
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-app-ly::app-ly loc1536::obj type1537::type fun1538::node arg1544::node)
    (inline app-ly?::bool ::obj)
    (app-ly-nil::app-ly)
    (inline app-ly-arg::node ::app-ly)
    (inline app-ly-arg-set! ::app-ly ::node)
    (inline app-ly-fun::node ::app-ly)
    (inline app-ly-fun-set! ::app-ly ::node)
    (inline app-ly-type::type ::app-ly)
    (inline app-ly-type-set! ::app-ly ::type)
    (inline app-ly-loc::obj ::app-ly))))

;; funcall
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-funcall::funcall loc1529::obj type1530::type fun1532::node args1533::obj strength1534::symbol)
    (inline funcall?::bool ::obj)
    (funcall-nil::funcall)
    (inline funcall-strength::symbol ::funcall)
    (inline funcall-strength-set! ::funcall ::symbol)
    (inline funcall-args::obj ::funcall)
    (inline funcall-args-set! ::funcall ::obj)
    (inline funcall-fun::node ::funcall)
    (inline funcall-fun-set! ::funcall ::node)
    (inline funcall-type::type ::funcall)
    (inline funcall-type-set! ::funcall ::type)
    (inline funcall-loc::obj ::funcall))))

;; extern
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-extern::extern loc1522::obj type1523::type side-effect?1524::obj key1525::obj expr*1526::pair-nil effect1527::obj)
    (inline extern?::bool ::obj)
    (extern-nil::extern)
    (inline extern-effect::obj ::extern)
    (inline extern-effect-set! ::extern ::obj)
    (inline extern-expr*::pair-nil ::extern)
    (inline extern-expr*-set! ::extern ::pair-nil)
    (inline extern-key::obj ::extern)
    (inline extern-key-set! ::extern ::obj)
    (inline extern-side-effect?::obj ::extern)
    (inline extern-side-effect?-set! ::extern ::obj)
    (inline extern-type::type ::extern)
    (inline extern-type-set! ::extern ::type)
    (inline extern-loc::obj ::extern))))

;; pragma
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-pragma::pragma loc1514::obj type1515::type side-effect?1516::obj key1517::obj expr*1518::pair-nil effect1519::obj format1520::bstring)
    (inline pragma?::bool ::obj)
    (pragma-nil::pragma)
    (inline pragma-format::bstring ::pragma)
    (inline pragma-effect::obj ::pragma)
    (inline pragma-effect-set! ::pragma ::obj)
    (inline pragma-expr*::pair-nil ::pragma)
    (inline pragma-expr*-set! ::pragma ::pair-nil)
    (inline pragma-key::obj ::pragma)
    (inline pragma-key-set! ::pragma ::obj)
    (inline pragma-side-effect?::obj ::pragma)
    (inline pragma-side-effect?-set! ::pragma ::obj)
    (inline pragma-type::type ::pragma)
    (inline pragma-type-set! ::pragma ::type)
    (inline pragma-loc::obj ::pragma))))

;; getfield
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-getfield::getfield loc1504::obj type1505::type side-effect?1506::obj key1507::obj expr*1508::pair-nil effect1509::obj fname1510::bstring ftype1511::type otype1512::type)
    (inline getfield?::bool ::obj)
    (getfield-nil::getfield)
    (inline getfield-otype::type ::getfield)
    (inline getfield-ftype::type ::getfield)
    (inline getfield-fname::bstring ::getfield)
    (inline getfield-effect::obj ::getfield)
    (inline getfield-effect-set! ::getfield ::obj)
    (inline getfield-expr*::pair-nil ::getfield)
    (inline getfield-expr*-set! ::getfield ::pair-nil)
    (inline getfield-key::obj ::getfield)
    (inline getfield-key-set! ::getfield ::obj)
    (inline getfield-side-effect?::obj ::getfield)
    (inline getfield-side-effect?-set! ::getfield ::obj)
    (inline getfield-type::type ::getfield)
    (inline getfield-type-set! ::getfield ::type)
    (inline getfield-loc::obj ::getfield))))

;; setfield
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-setfield::setfield loc1494::obj type1495::type side-effect?1496::obj key1497::obj expr*1498::pair-nil effect1499::obj fname1500::bstring ftype1501::type otype1502::type)
    (inline setfield?::bool ::obj)
    (setfield-nil::setfield)
    (inline setfield-otype::type ::setfield)
    (inline setfield-ftype::type ::setfield)
    (inline setfield-fname::bstring ::setfield)
    (inline setfield-effect::obj ::setfield)
    (inline setfield-effect-set! ::setfield ::obj)
    (inline setfield-expr*::pair-nil ::setfield)
    (inline setfield-expr*-set! ::setfield ::pair-nil)
    (inline setfield-key::obj ::setfield)
    (inline setfield-key-set! ::setfield ::obj)
    (inline setfield-side-effect?::obj ::setfield)
    (inline setfield-side-effect?-set! ::setfield ::obj)
    (inline setfield-type::type ::setfield)
    (inline setfield-type-set! ::setfield ::type)
    (inline setfield-loc::obj ::setfield))))

;; new
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-new::new loc1486::obj type1487::type side-effect?1488::obj key1489::obj expr*1490::pair-nil effect1491::obj args-type1492::pair-nil)
    (inline new?::bool ::obj)
    (new-nil::new)
    (inline new-args-type::pair-nil ::new)
    (inline new-args-type-set! ::new ::pair-nil)
    (inline new-effect::obj ::new)
    (inline new-effect-set! ::new ::obj)
    (inline new-expr*::pair-nil ::new)
    (inline new-expr*-set! ::new ::pair-nil)
    (inline new-key::obj ::new)
    (inline new-key-set! ::new ::obj)
    (inline new-side-effect?::obj ::new)
    (inline new-side-effect?-set! ::new ::obj)
    (inline new-type::type ::new)
    (inline new-type-set! ::new ::type)
    (inline new-loc::obj ::new))))

;; valloc
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-valloc::valloc loc1476::obj type1477::type side-effect?1478::obj key1479::obj expr*1480::pair-nil effect1481::obj c-heap-format1482::bstring ftype1483::type otype1484::type)
    (inline valloc?::bool ::obj)
    (valloc-nil::valloc)
    (inline valloc-otype::type ::valloc)
    (inline valloc-ftype::type ::valloc)
    (inline valloc-c-heap-format::bstring ::valloc)
    (inline valloc-effect::obj ::valloc)
    (inline valloc-effect-set! ::valloc ::obj)
    (inline valloc-expr*::pair-nil ::valloc)
    (inline valloc-expr*-set! ::valloc ::pair-nil)
    (inline valloc-key::obj ::valloc)
    (inline valloc-key-set! ::valloc ::obj)
    (inline valloc-side-effect?::obj ::valloc)
    (inline valloc-side-effect?-set! ::valloc ::obj)
    (inline valloc-type::type ::valloc)
    (inline valloc-type-set! ::valloc ::type)
    (inline valloc-loc::obj ::valloc))))

;; vref
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-vref::vref loc1465::obj type1466::type side-effect?1467::obj key1468::obj expr*1469::pair-nil effect1470::obj c-format1471::bstring ftype1472::type otype1473::type vtype1474::type)
    (inline vref?::bool ::obj)
    (vref-nil::vref)
    (inline vref-vtype::type ::vref)
    (inline vref-otype::type ::vref)
    (inline vref-ftype::type ::vref)
    (inline vref-ftype-set! ::vref ::type)
    (inline vref-c-format::bstring ::vref)
    (inline vref-effect::obj ::vref)
    (inline vref-effect-set! ::vref ::obj)
    (inline vref-expr*::pair-nil ::vref)
    (inline vref-expr*-set! ::vref ::pair-nil)
    (inline vref-key::obj ::vref)
    (inline vref-key-set! ::vref ::obj)
    (inline vref-side-effect?::obj ::vref)
    (inline vref-side-effect?-set! ::vref ::obj)
    (inline vref-type::type ::vref)
    (inline vref-type-set! ::vref ::type)
    (inline vref-loc::obj ::vref))))

;; vset!
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-vset!::vset! loc1454::obj type1455::type side-effect?1456::obj key1457::obj expr*1458::pair-nil effect1459::obj c-format1460::bstring ftype1461::type otype1462::type vtype1463::type)
    (inline vset!?::bool ::obj)
    (vset!-nil::vset!)
    (inline vset!-vtype::type ::vset!)
    (inline vset!-otype::type ::vset!)
    (inline vset!-ftype::type ::vset!)
    (inline vset!-ftype-set! ::vset! ::type)
    (inline vset!-c-format::bstring ::vset!)
    (inline vset!-effect::obj ::vset!)
    (inline vset!-effect-set! ::vset! ::obj)
    (inline vset!-expr*::pair-nil ::vset!)
    (inline vset!-expr*-set! ::vset! ::pair-nil)
    (inline vset!-key::obj ::vset!)
    (inline vset!-key-set! ::vset! ::obj)
    (inline vset!-side-effect?::obj ::vset!)
    (inline vset!-side-effect?-set! ::vset! ::obj)
    (inline vset!-type::type ::vset!)
    (inline vset!-type-set! ::vset! ::type)
    (inline vset!-loc::obj ::vset!))))

;; vlength
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-vlength::vlength loc1445::obj type1446::type side-effect?1447::obj key1448::obj expr*1449::pair-nil effect1450::obj c-format1451::bstring vtype1452::type)
    (inline vlength?::bool ::obj)
    (vlength-nil::vlength)
    (inline vlength-vtype::type ::vlength)
    (inline vlength-c-format::bstring ::vlength)
    (inline vlength-effect::obj ::vlength)
    (inline vlength-effect-set! ::vlength ::obj)
    (inline vlength-expr*::pair-nil ::vlength)
    (inline vlength-expr*-set! ::vlength ::pair-nil)
    (inline vlength-key::obj ::vlength)
    (inline vlength-key-set! ::vlength ::obj)
    (inline vlength-side-effect?::obj ::vlength)
    (inline vlength-side-effect?-set! ::vlength ::obj)
    (inline vlength-type::type ::vlength)
    (inline vlength-type-set! ::vlength ::type)
    (inline vlength-loc::obj ::vlength))))

;; isa
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-isa::isa loc1437::obj type1438::type side-effect?1439::obj key1440::obj expr*1441::pair-nil effect1442::obj class1443::type)
    (inline isa?::bool ::obj)
    (isa-nil::isa)
    (inline isa-class::type ::isa)
    (inline isa-effect::obj ::isa)
    (inline isa-effect-set! ::isa ::obj)
    (inline isa-expr*::pair-nil ::isa)
    (inline isa-expr*-set! ::isa ::pair-nil)
    (inline isa-key::obj ::isa)
    (inline isa-key-set! ::isa ::obj)
    (inline isa-side-effect?::obj ::isa)
    (inline isa-side-effect?-set! ::isa ::obj)
    (inline isa-type::type ::isa)
    (inline isa-type-set! ::isa ::type)
    (inline isa-loc::obj ::isa))))

;; cast-null
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-cast-null::cast-null loc1430::obj type1431::type side-effect?1432::obj key1433::obj expr*1434::pair-nil effect1435::obj)
    (inline cast-null?::bool ::obj)
    (cast-null-nil::cast-null)
    (inline cast-null-effect::obj ::cast-null)
    (inline cast-null-effect-set! ::cast-null ::obj)
    (inline cast-null-expr*::pair-nil ::cast-null)
    (inline cast-null-expr*-set! ::cast-null ::pair-nil)
    (inline cast-null-key::obj ::cast-null)
    (inline cast-null-key-set! ::cast-null ::obj)
    (inline cast-null-side-effect?::obj ::cast-null)
    (inline cast-null-side-effect?-set! ::cast-null ::obj)
    (inline cast-null-type::type ::cast-null)
    (inline cast-null-type-set! ::cast-null ::type)
    (inline cast-null-loc::obj ::cast-null))))

;; cast
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-cast::cast loc1425::obj type1426::type arg1428::node)
    (inline cast?::bool ::obj)
    (cast-nil::cast)
    (inline cast-arg::node ::cast)
    (inline cast-arg-set! ::cast ::node)
    (inline cast-type::type ::cast)
    (inline cast-type-set! ::cast ::type)
    (inline cast-loc::obj ::cast))))

;; setq
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-setq::setq loc1420::obj type1421::type var1422::var value1423::node)
    (inline setq?::bool ::obj)
    (setq-nil::setq)
    (inline setq-value::node ::setq)
    (inline setq-value-set! ::setq ::node)
    (inline setq-var::var ::setq)
    (inline setq-var-set! ::setq ::var)
    (inline setq-type::type ::setq)
    (inline setq-type-set! ::setq ::type)
    (inline setq-loc::obj ::setq))))

;; conditional
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-conditional::conditional loc1411::obj type1412::type side-effect?1413::obj key1414::obj test1415::node true1416::node false1417::node)
    (inline conditional?::bool ::obj)
    (conditional-nil::conditional)
    (inline conditional-false::node ::conditional)
    (inline conditional-false-set! ::conditional ::node)
    (inline conditional-true::node ::conditional)
    (inline conditional-true-set! ::conditional ::node)
    (inline conditional-test::node ::conditional)
    (inline conditional-test-set! ::conditional ::node)
    (inline conditional-key::obj ::conditional)
    (inline conditional-key-set! ::conditional ::obj)
    (inline conditional-side-effect?::obj ::conditional)
    (inline conditional-side-effect?-set! ::conditional ::obj)
    (inline conditional-type::type ::conditional)
    (inline conditional-type-set! ::conditional ::type)
    (inline conditional-loc::obj ::conditional))))

;; fail
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-fail::fail loc1405::obj type1406::type proc1407::node msg1408::node obj1409::node)
    (inline fail?::bool ::obj)
    (fail-nil::fail)
    (inline fail-obj::node ::fail)
    (inline fail-obj-set! ::fail ::node)
    (inline fail-msg::node ::fail)
    (inline fail-msg-set! ::fail ::node)
    (inline fail-proc::node ::fail)
    (inline fail-proc-set! ::fail ::node)
    (inline fail-type::type ::fail)
    (inline fail-type-set! ::fail ::type)
    (inline fail-loc::obj ::fail))))

;; select
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-select::select loc1395::obj type1396::type side-effect?1397::obj key1398::obj test1401::node clauses1402::obj item-type1403::type)
    (inline select?::bool ::obj)
    (select-nil::select)
    (inline select-item-type::type ::select)
    (inline select-clauses::obj ::select)
    (inline select-test::node ::select)
    (inline select-test-set! ::select ::node)
    (inline select-key::obj ::select)
    (inline select-key-set! ::select ::obj)
    (inline select-side-effect?::obj ::select)
    (inline select-side-effect?-set! ::select ::obj)
    (inline select-type::type ::select)
    (inline select-type-set! ::select ::type)
    (inline select-loc::obj ::select))))

;; let-fun
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-let-fun::let-fun loc1388::obj type1389::type side-effect?1390::obj key1391::obj locals1392::obj body1393::node)
    (inline let-fun?::bool ::obj)
    (let-fun-nil::let-fun)
    (inline let-fun-body::node ::let-fun)
    (inline let-fun-body-set! ::let-fun ::node)
    (inline let-fun-locals::obj ::let-fun)
    (inline let-fun-locals-set! ::let-fun ::obj)
    (inline let-fun-key::obj ::let-fun)
    (inline let-fun-key-set! ::let-fun ::obj)
    (inline let-fun-side-effect?::obj ::let-fun)
    (inline let-fun-side-effect?-set! ::let-fun ::obj)
    (inline let-fun-type::type ::let-fun)
    (inline let-fun-type-set! ::let-fun ::type)
    (inline let-fun-loc::obj ::let-fun))))

;; let-var
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-let-var::let-var loc1380::obj type1381::type side-effect?1382::obj key1383::obj bindings1384::obj body1385::node removable?1386::bool)
    (inline let-var?::bool ::obj)
    (let-var-nil::let-var)
    (inline let-var-removable?::bool ::let-var)
    (inline let-var-removable?-set! ::let-var ::bool)
    (inline let-var-body::node ::let-var)
    (inline let-var-body-set! ::let-var ::node)
    (inline let-var-bindings::obj ::let-var)
    (inline let-var-bindings-set! ::let-var ::obj)
    (inline let-var-key::obj ::let-var)
    (inline let-var-key-set! ::let-var ::obj)
    (inline let-var-side-effect?::obj ::let-var)
    (inline let-var-side-effect?-set! ::let-var ::obj)
    (inline let-var-type::type ::let-var)
    (inline let-var-type-set! ::let-var ::type)
    (inline let-var-loc::obj ::let-var))))

;; set-ex-it
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-set-ex-it::set-ex-it loc1375::obj type1376::type var1377::var body1378::node)
    (inline set-ex-it?::bool ::obj)
    (set-ex-it-nil::set-ex-it)
    (inline set-ex-it-body::node ::set-ex-it)
    (inline set-ex-it-body-set! ::set-ex-it ::node)
    (inline set-ex-it-var::var ::set-ex-it)
    (inline set-ex-it-var-set! ::set-ex-it ::var)
    (inline set-ex-it-type::type ::set-ex-it)
    (inline set-ex-it-type-set! ::set-ex-it ::type)
    (inline set-ex-it-loc::obj ::set-ex-it))))

;; jump-ex-it
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-jump-ex-it::jump-ex-it loc1370::obj type1371::type exit1372::node value1373::node)
    (inline jump-ex-it?::bool ::obj)
    (jump-ex-it-nil::jump-ex-it)
    (inline jump-ex-it-value::node ::jump-ex-it)
    (inline jump-ex-it-value-set! ::jump-ex-it ::node)
    (inline jump-ex-it-exit::node ::jump-ex-it)
    (inline jump-ex-it-exit-set! ::jump-ex-it ::node)
    (inline jump-ex-it-type::type ::jump-ex-it)
    (inline jump-ex-it-type-set! ::jump-ex-it ::type)
    (inline jump-ex-it-loc::obj ::jump-ex-it))))

;; make-box
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-make-box::make-box loc1364::obj type1365::type side-effect?1366::obj key1367::obj value1368::node)
    (inline make-box?::bool ::obj)
    (make-box-nil::make-box)
    (inline make-box-value::node ::make-box)
    (inline make-box-value-set! ::make-box ::node)
    (inline make-box-key::obj ::make-box)
    (inline make-box-key-set! ::make-box ::obj)
    (inline make-box-side-effect?::obj ::make-box)
    (inline make-box-side-effect?-set! ::make-box ::obj)
    (inline make-box-type::type ::make-box)
    (inline make-box-type-set! ::make-box ::type)
    (inline make-box-loc::obj ::make-box))))

;; box-ref
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-box-ref::box-ref loc1358::obj type1359::type side-effect?1360::obj key1361::obj var1362::var)
    (inline box-ref?::bool ::obj)
    (box-ref-nil::box-ref)
    (inline box-ref-var::var ::box-ref)
    (inline box-ref-var-set! ::box-ref ::var)
    (inline box-ref-key::obj ::box-ref)
    (inline box-ref-key-set! ::box-ref ::obj)
    (inline box-ref-side-effect?::obj ::box-ref)
    (inline box-ref-side-effect?-set! ::box-ref ::obj)
    (inline box-ref-type::type ::box-ref)
    (inline box-ref-type-set! ::box-ref ::type)
    (inline box-ref-loc::obj ::box-ref))))

;; box-set!
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (export
    (inline make-box-set!::box-set! loc1353::obj type1354::type var1355::var value1356::node)
    (inline box-set!?::bool ::obj)
    (box-set!-nil::box-set!)
    (inline box-set!-value::node ::box-set!)
    (inline box-set!-value-set! ::box-set! ::node)
    (inline box-set!-var::var ::box-set!)
    (inline box-set!-var-set! ::box-set! ::var)
    (inline box-set!-type::type ::box-set!)
    (inline box-set!-type-set! ::box-set! ::type)
    (inline box-set!-loc::obj ::box-set!)))))

;; The definitions
(cond-expand (bigloo-class-sans
;; node
(define-inline (make-node::node loc1580::obj type1581::type) (instantiate::node (loc loc1580) (type type1581)))
(define-inline (node?::bool obj::obj) ((@ isa? __object) obj (@ node ast_node)))
(define (node-nil::node) (class-nil (@ node ast_node)))
(define-inline (node-type::type o::node) (-> |#!bigloo_wallow| o type))
(define-inline (node-type-set! o::node v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (node-loc::obj o::node) (-> |#!bigloo_wallow| o loc))
(define-inline (node-loc-set! o::node v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; node/effect
(define-inline (make-node/effect::node/effect loc1575::obj type1576::type side-effect?1577::obj key1578::obj) (instantiate::node/effect (loc loc1575) (type type1576) (side-effect? side-effect?1577) (key key1578)))
(define-inline (node/effect?::bool obj::obj) ((@ isa? __object) obj (@ node/effect ast_node)))
(define (node/effect-nil::node/effect) (class-nil (@ node/effect ast_node)))
(define-inline (node/effect-key::obj o::node/effect) (-> |#!bigloo_wallow| o key))
(define-inline (node/effect-key-set! o::node/effect v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (node/effect-side-effect?::obj o::node/effect) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (node/effect-side-effect?-set! o::node/effect v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (node/effect-type::type o::node/effect) (-> |#!bigloo_wallow| o type))
(define-inline (node/effect-type-set! o::node/effect v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (node/effect-loc::obj o::node/effect) (-> |#!bigloo_wallow| o loc))
(define-inline (node/effect-loc-set! o::node/effect v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; atom
(define-inline (make-atom::atom loc1571::obj type1572::type value1573::obj) (instantiate::atom (loc loc1571) (type type1572) (value value1573)))
(define-inline (atom?::bool obj::obj) ((@ isa? __object) obj (@ atom ast_node)))
(define (atom-nil::atom) (class-nil (@ atom ast_node)))
(define-inline (atom-value::obj o::atom) (-> |#!bigloo_wallow| o value))
(define-inline (atom-value-set! o::atom v::obj) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (atom-type::type o::atom) (-> |#!bigloo_wallow| o type))
(define-inline (atom-type-set! o::atom v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (atom-loc::obj o::atom) (-> |#!bigloo_wallow| o loc))
(define-inline (atom-loc-set! o::atom v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; var
(define-inline (make-var::var loc1567::obj type1568::type variable1569::variable) (instantiate::var (loc loc1567) (type type1568) (variable variable1569)))
(define-inline (var?::bool obj::obj) ((@ isa? __object) obj (@ var ast_node)))
(define (var-nil::var) (class-nil (@ var ast_node)))
(define-inline (var-variable::variable o::var) (-> |#!bigloo_wallow| o variable))
(define-inline (var-variable-set! o::var v::variable) (set! (-> |#!bigloo_wallow| o variable) v))
(define-inline (var-type::type o::var) (-> |#!bigloo_wallow| o type))
(define-inline (var-type-set! o::var v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (var-loc::obj o::var) (-> |#!bigloo_wallow| o loc))
(define-inline (var-loc-set! o::var v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; closure
(define-inline (make-closure::closure loc1563::obj type1564::type variable1565::variable) (instantiate::closure (loc loc1563) (type type1564) (variable variable1565)))
(define-inline (closure?::bool obj::obj) ((@ isa? __object) obj (@ closure ast_node)))
(define (closure-nil::closure) (class-nil (@ closure ast_node)))
(define-inline (closure-variable::variable o::closure) (-> |#!bigloo_wallow| o variable))
(define-inline (closure-variable-set! o::closure v::variable) (set! (-> |#!bigloo_wallow| o variable) v))
(define-inline (closure-type::type o::closure) (-> |#!bigloo_wallow| o type))
(define-inline (closure-type-set! o::closure v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (closure-loc::obj o::closure) (-> |#!bigloo_wallow| o loc))
(define-inline (closure-loc-set! o::closure v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; kwote
(define-inline (make-kwote::kwote loc1559::obj type1560::type value1561::obj) (instantiate::kwote (loc loc1559) (type type1560) (value value1561)))
(define-inline (kwote?::bool obj::obj) ((@ isa? __object) obj (@ kwote ast_node)))
(define (kwote-nil::kwote) (class-nil (@ kwote ast_node)))
(define-inline (kwote-value::obj o::kwote) (-> |#!bigloo_wallow| o value))
(define-inline (kwote-value-set! o::kwote v::obj) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (kwote-type::type o::kwote) (-> |#!bigloo_wallow| o type))
(define-inline (kwote-type-set! o::kwote v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (kwote-loc::obj o::kwote) (-> |#!bigloo_wallow| o loc))
(define-inline (kwote-loc-set! o::kwote v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; sequence
(define-inline (make-sequence::sequence loc1553::obj type1554::type side-effect?1555::obj key1556::obj nodes1557::obj) (instantiate::sequence (loc loc1553) (type type1554) (side-effect? side-effect?1555) (key key1556) (nodes nodes1557)))
(define-inline (sequence?::bool obj::obj) ((@ isa? __object) obj (@ sequence ast_node)))
(define (sequence-nil::sequence) (class-nil (@ sequence ast_node)))
(define-inline (sequence-nodes::obj o::sequence) (-> |#!bigloo_wallow| o nodes))
(define-inline (sequence-nodes-set! o::sequence v::obj) (set! (-> |#!bigloo_wallow| o nodes) v))
(define-inline (sequence-key::obj o::sequence) (-> |#!bigloo_wallow| o key))
(define-inline (sequence-key-set! o::sequence v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (sequence-side-effect?::obj o::sequence) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (sequence-side-effect?-set! o::sequence v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (sequence-type::type o::sequence) (-> |#!bigloo_wallow| o type))
(define-inline (sequence-type-set! o::sequence v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (sequence-loc::obj o::sequence) (-> |#!bigloo_wallow| o loc))
(define-inline (sequence-loc-set! o::sequence v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; app
(define-inline (make-app::app loc1546::obj type1547::type side-effect?1548::obj key1549::obj fun1550::var args1551::obj) (instantiate::app (loc loc1546) (type type1547) (side-effect? side-effect?1548) (key key1549) (fun fun1550) (args args1551)))
(define-inline (app?::bool obj::obj) ((@ isa? __object) obj (@ app ast_node)))
(define (app-nil::app) (class-nil (@ app ast_node)))
(define-inline (app-args::obj o::app) (-> |#!bigloo_wallow| o args))
(define-inline (app-args-set! o::app v::obj) (set! (-> |#!bigloo_wallow| o args) v))
(define-inline (app-fun::var o::app) (-> |#!bigloo_wallow| o fun))
(define-inline (app-fun-set! o::app v::var) (set! (-> |#!bigloo_wallow| o fun) v))
(define-inline (app-key::obj o::app) (-> |#!bigloo_wallow| o key))
(define-inline (app-key-set! o::app v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (app-side-effect?::obj o::app) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (app-side-effect?-set! o::app v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (app-type::type o::app) (-> |#!bigloo_wallow| o type))
(define-inline (app-type-set! o::app v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (app-loc::obj o::app) (-> |#!bigloo_wallow| o loc))
(define-inline (app-loc-set! o::app v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; app-ly
(define-inline (make-app-ly::app-ly loc1536::obj type1537::type fun1538::node arg1544::node) (instantiate::app-ly (loc loc1536) (type type1537) (fun fun1538) (arg arg1544)))
(define-inline (app-ly?::bool obj::obj) ((@ isa? __object) obj (@ app-ly ast_node)))
(define (app-ly-nil::app-ly) (class-nil (@ app-ly ast_node)))
(define-inline (app-ly-arg::node o::app-ly) (-> |#!bigloo_wallow| o arg))
(define-inline (app-ly-arg-set! o::app-ly v::node) (set! (-> |#!bigloo_wallow| o arg) v))
(define-inline (app-ly-fun::node o::app-ly) (-> |#!bigloo_wallow| o fun))
(define-inline (app-ly-fun-set! o::app-ly v::node) (set! (-> |#!bigloo_wallow| o fun) v))
(define-inline (app-ly-type::type o::app-ly) (-> |#!bigloo_wallow| o type))
(define-inline (app-ly-type-set! o::app-ly v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (app-ly-loc::obj o::app-ly) (-> |#!bigloo_wallow| o loc))
(define-inline (app-ly-loc-set! o::app-ly v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; funcall
(define-inline (make-funcall::funcall loc1529::obj type1530::type fun1532::node args1533::obj strength1534::symbol) (instantiate::funcall (loc loc1529) (type type1530) (fun fun1532) (args args1533) (strength strength1534)))
(define-inline (funcall?::bool obj::obj) ((@ isa? __object) obj (@ funcall ast_node)))
(define (funcall-nil::funcall) (class-nil (@ funcall ast_node)))
(define-inline (funcall-strength::symbol o::funcall) (-> |#!bigloo_wallow| o strength))
(define-inline (funcall-strength-set! o::funcall v::symbol) (set! (-> |#!bigloo_wallow| o strength) v))
(define-inline (funcall-args::obj o::funcall) (-> |#!bigloo_wallow| o args))
(define-inline (funcall-args-set! o::funcall v::obj) (set! (-> |#!bigloo_wallow| o args) v))
(define-inline (funcall-fun::node o::funcall) (-> |#!bigloo_wallow| o fun))
(define-inline (funcall-fun-set! o::funcall v::node) (set! (-> |#!bigloo_wallow| o fun) v))
(define-inline (funcall-type::type o::funcall) (-> |#!bigloo_wallow| o type))
(define-inline (funcall-type-set! o::funcall v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (funcall-loc::obj o::funcall) (-> |#!bigloo_wallow| o loc))
(define-inline (funcall-loc-set! o::funcall v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; extern
(define-inline (make-extern::extern loc1522::obj type1523::type side-effect?1524::obj key1525::obj expr*1526::pair-nil effect1527::obj) (instantiate::extern (loc loc1522) (type type1523) (side-effect? side-effect?1524) (key key1525) (expr* expr*1526) (effect effect1527)))
(define-inline (extern?::bool obj::obj) ((@ isa? __object) obj (@ extern ast_node)))
(define (extern-nil::extern) (class-nil (@ extern ast_node)))
(define-inline (extern-effect::obj o::extern) (-> |#!bigloo_wallow| o effect))
(define-inline (extern-effect-set! o::extern v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (extern-expr*::pair-nil o::extern) (-> |#!bigloo_wallow| o expr*))
(define-inline (extern-expr*-set! o::extern v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (extern-key::obj o::extern) (-> |#!bigloo_wallow| o key))
(define-inline (extern-key-set! o::extern v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (extern-side-effect?::obj o::extern) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (extern-side-effect?-set! o::extern v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (extern-type::type o::extern) (-> |#!bigloo_wallow| o type))
(define-inline (extern-type-set! o::extern v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (extern-loc::obj o::extern) (-> |#!bigloo_wallow| o loc))
(define-inline (extern-loc-set! o::extern v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; pragma
(define-inline (make-pragma::pragma loc1514::obj type1515::type side-effect?1516::obj key1517::obj expr*1518::pair-nil effect1519::obj format1520::bstring) (instantiate::pragma (loc loc1514) (type type1515) (side-effect? side-effect?1516) (key key1517) (expr* expr*1518) (effect effect1519) (format format1520)))
(define-inline (pragma?::bool obj::obj) ((@ isa? __object) obj (@ pragma ast_node)))
(define (pragma-nil::pragma) (class-nil (@ pragma ast_node)))
(define-inline (pragma-format::bstring o::pragma) (-> |#!bigloo_wallow| o format))
(define-inline (pragma-format-set! o::pragma v::bstring) (set! (-> |#!bigloo_wallow| o format) v))
(define-inline (pragma-effect::obj o::pragma) (-> |#!bigloo_wallow| o effect))
(define-inline (pragma-effect-set! o::pragma v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (pragma-expr*::pair-nil o::pragma) (-> |#!bigloo_wallow| o expr*))
(define-inline (pragma-expr*-set! o::pragma v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (pragma-key::obj o::pragma) (-> |#!bigloo_wallow| o key))
(define-inline (pragma-key-set! o::pragma v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (pragma-side-effect?::obj o::pragma) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (pragma-side-effect?-set! o::pragma v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (pragma-type::type o::pragma) (-> |#!bigloo_wallow| o type))
(define-inline (pragma-type-set! o::pragma v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (pragma-loc::obj o::pragma) (-> |#!bigloo_wallow| o loc))
(define-inline (pragma-loc-set! o::pragma v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; getfield
(define-inline (make-getfield::getfield loc1504::obj type1505::type side-effect?1506::obj key1507::obj expr*1508::pair-nil effect1509::obj fname1510::bstring ftype1511::type otype1512::type) (instantiate::getfield (loc loc1504) (type type1505) (side-effect? side-effect?1506) (key key1507) (expr* expr*1508) (effect effect1509) (fname fname1510) (ftype ftype1511) (otype otype1512)))
(define-inline (getfield?::bool obj::obj) ((@ isa? __object) obj (@ getfield ast_node)))
(define (getfield-nil::getfield) (class-nil (@ getfield ast_node)))
(define-inline (getfield-otype::type o::getfield) (-> |#!bigloo_wallow| o otype))
(define-inline (getfield-otype-set! o::getfield v::type) (set! (-> |#!bigloo_wallow| o otype) v))
(define-inline (getfield-ftype::type o::getfield) (-> |#!bigloo_wallow| o ftype))
(define-inline (getfield-ftype-set! o::getfield v::type) (set! (-> |#!bigloo_wallow| o ftype) v))
(define-inline (getfield-fname::bstring o::getfield) (-> |#!bigloo_wallow| o fname))
(define-inline (getfield-fname-set! o::getfield v::bstring) (set! (-> |#!bigloo_wallow| o fname) v))
(define-inline (getfield-effect::obj o::getfield) (-> |#!bigloo_wallow| o effect))
(define-inline (getfield-effect-set! o::getfield v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (getfield-expr*::pair-nil o::getfield) (-> |#!bigloo_wallow| o expr*))
(define-inline (getfield-expr*-set! o::getfield v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (getfield-key::obj o::getfield) (-> |#!bigloo_wallow| o key))
(define-inline (getfield-key-set! o::getfield v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (getfield-side-effect?::obj o::getfield) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (getfield-side-effect?-set! o::getfield v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (getfield-type::type o::getfield) (-> |#!bigloo_wallow| o type))
(define-inline (getfield-type-set! o::getfield v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (getfield-loc::obj o::getfield) (-> |#!bigloo_wallow| o loc))
(define-inline (getfield-loc-set! o::getfield v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; setfield
(define-inline (make-setfield::setfield loc1494::obj type1495::type side-effect?1496::obj key1497::obj expr*1498::pair-nil effect1499::obj fname1500::bstring ftype1501::type otype1502::type) (instantiate::setfield (loc loc1494) (type type1495) (side-effect? side-effect?1496) (key key1497) (expr* expr*1498) (effect effect1499) (fname fname1500) (ftype ftype1501) (otype otype1502)))
(define-inline (setfield?::bool obj::obj) ((@ isa? __object) obj (@ setfield ast_node)))
(define (setfield-nil::setfield) (class-nil (@ setfield ast_node)))
(define-inline (setfield-otype::type o::setfield) (-> |#!bigloo_wallow| o otype))
(define-inline (setfield-otype-set! o::setfield v::type) (set! (-> |#!bigloo_wallow| o otype) v))
(define-inline (setfield-ftype::type o::setfield) (-> |#!bigloo_wallow| o ftype))
(define-inline (setfield-ftype-set! o::setfield v::type) (set! (-> |#!bigloo_wallow| o ftype) v))
(define-inline (setfield-fname::bstring o::setfield) (-> |#!bigloo_wallow| o fname))
(define-inline (setfield-fname-set! o::setfield v::bstring) (set! (-> |#!bigloo_wallow| o fname) v))
(define-inline (setfield-effect::obj o::setfield) (-> |#!bigloo_wallow| o effect))
(define-inline (setfield-effect-set! o::setfield v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (setfield-expr*::pair-nil o::setfield) (-> |#!bigloo_wallow| o expr*))
(define-inline (setfield-expr*-set! o::setfield v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (setfield-key::obj o::setfield) (-> |#!bigloo_wallow| o key))
(define-inline (setfield-key-set! o::setfield v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (setfield-side-effect?::obj o::setfield) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (setfield-side-effect?-set! o::setfield v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (setfield-type::type o::setfield) (-> |#!bigloo_wallow| o type))
(define-inline (setfield-type-set! o::setfield v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (setfield-loc::obj o::setfield) (-> |#!bigloo_wallow| o loc))
(define-inline (setfield-loc-set! o::setfield v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; new
(define-inline (make-new::new loc1486::obj type1487::type side-effect?1488::obj key1489::obj expr*1490::pair-nil effect1491::obj args-type1492::pair-nil) (instantiate::new (loc loc1486) (type type1487) (side-effect? side-effect?1488) (key key1489) (expr* expr*1490) (effect effect1491) (args-type args-type1492)))
(define-inline (new?::bool obj::obj) ((@ isa? __object) obj (@ new ast_node)))
(define (new-nil::new) (class-nil (@ new ast_node)))
(define-inline (new-args-type::pair-nil o::new) (-> |#!bigloo_wallow| o args-type))
(define-inline (new-args-type-set! o::new v::pair-nil) (set! (-> |#!bigloo_wallow| o args-type) v))
(define-inline (new-effect::obj o::new) (-> |#!bigloo_wallow| o effect))
(define-inline (new-effect-set! o::new v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (new-expr*::pair-nil o::new) (-> |#!bigloo_wallow| o expr*))
(define-inline (new-expr*-set! o::new v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (new-key::obj o::new) (-> |#!bigloo_wallow| o key))
(define-inline (new-key-set! o::new v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (new-side-effect?::obj o::new) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (new-side-effect?-set! o::new v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (new-type::type o::new) (-> |#!bigloo_wallow| o type))
(define-inline (new-type-set! o::new v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (new-loc::obj o::new) (-> |#!bigloo_wallow| o loc))
(define-inline (new-loc-set! o::new v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; valloc
(define-inline (make-valloc::valloc loc1476::obj type1477::type side-effect?1478::obj key1479::obj expr*1480::pair-nil effect1481::obj c-heap-format1482::bstring ftype1483::type otype1484::type) (instantiate::valloc (loc loc1476) (type type1477) (side-effect? side-effect?1478) (key key1479) (expr* expr*1480) (effect effect1481) (c-heap-format c-heap-format1482) (ftype ftype1483) (otype otype1484)))
(define-inline (valloc?::bool obj::obj) ((@ isa? __object) obj (@ valloc ast_node)))
(define (valloc-nil::valloc) (class-nil (@ valloc ast_node)))
(define-inline (valloc-otype::type o::valloc) (-> |#!bigloo_wallow| o otype))
(define-inline (valloc-otype-set! o::valloc v::type) (set! (-> |#!bigloo_wallow| o otype) v))
(define-inline (valloc-ftype::type o::valloc) (-> |#!bigloo_wallow| o ftype))
(define-inline (valloc-ftype-set! o::valloc v::type) (set! (-> |#!bigloo_wallow| o ftype) v))
(define-inline (valloc-c-heap-format::bstring o::valloc) (-> |#!bigloo_wallow| o c-heap-format))
(define-inline (valloc-c-heap-format-set! o::valloc v::bstring) (set! (-> |#!bigloo_wallow| o c-heap-format) v))
(define-inline (valloc-effect::obj o::valloc) (-> |#!bigloo_wallow| o effect))
(define-inline (valloc-effect-set! o::valloc v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (valloc-expr*::pair-nil o::valloc) (-> |#!bigloo_wallow| o expr*))
(define-inline (valloc-expr*-set! o::valloc v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (valloc-key::obj o::valloc) (-> |#!bigloo_wallow| o key))
(define-inline (valloc-key-set! o::valloc v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (valloc-side-effect?::obj o::valloc) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (valloc-side-effect?-set! o::valloc v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (valloc-type::type o::valloc) (-> |#!bigloo_wallow| o type))
(define-inline (valloc-type-set! o::valloc v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (valloc-loc::obj o::valloc) (-> |#!bigloo_wallow| o loc))
(define-inline (valloc-loc-set! o::valloc v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; vref
(define-inline (make-vref::vref loc1465::obj type1466::type side-effect?1467::obj key1468::obj expr*1469::pair-nil effect1470::obj c-format1471::bstring ftype1472::type otype1473::type vtype1474::type) (instantiate::vref (loc loc1465) (type type1466) (side-effect? side-effect?1467) (key key1468) (expr* expr*1469) (effect effect1470) (c-format c-format1471) (ftype ftype1472) (otype otype1473) (vtype vtype1474)))
(define-inline (vref?::bool obj::obj) ((@ isa? __object) obj (@ vref ast_node)))
(define (vref-nil::vref) (class-nil (@ vref ast_node)))
(define-inline (vref-vtype::type o::vref) (-> |#!bigloo_wallow| o vtype))
(define-inline (vref-vtype-set! o::vref v::type) (set! (-> |#!bigloo_wallow| o vtype) v))
(define-inline (vref-otype::type o::vref) (-> |#!bigloo_wallow| o otype))
(define-inline (vref-otype-set! o::vref v::type) (set! (-> |#!bigloo_wallow| o otype) v))
(define-inline (vref-ftype::type o::vref) (-> |#!bigloo_wallow| o ftype))
(define-inline (vref-ftype-set! o::vref v::type) (set! (-> |#!bigloo_wallow| o ftype) v))
(define-inline (vref-c-format::bstring o::vref) (-> |#!bigloo_wallow| o c-format))
(define-inline (vref-c-format-set! o::vref v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (vref-effect::obj o::vref) (-> |#!bigloo_wallow| o effect))
(define-inline (vref-effect-set! o::vref v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (vref-expr*::pair-nil o::vref) (-> |#!bigloo_wallow| o expr*))
(define-inline (vref-expr*-set! o::vref v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (vref-key::obj o::vref) (-> |#!bigloo_wallow| o key))
(define-inline (vref-key-set! o::vref v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (vref-side-effect?::obj o::vref) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (vref-side-effect?-set! o::vref v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (vref-type::type o::vref) (-> |#!bigloo_wallow| o type))
(define-inline (vref-type-set! o::vref v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (vref-loc::obj o::vref) (-> |#!bigloo_wallow| o loc))
(define-inline (vref-loc-set! o::vref v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; vset!
(define-inline (make-vset!::vset! loc1454::obj type1455::type side-effect?1456::obj key1457::obj expr*1458::pair-nil effect1459::obj c-format1460::bstring ftype1461::type otype1462::type vtype1463::type) (instantiate::vset! (loc loc1454) (type type1455) (side-effect? side-effect?1456) (key key1457) (expr* expr*1458) (effect effect1459) (c-format c-format1460) (ftype ftype1461) (otype otype1462) (vtype vtype1463)))
(define-inline (vset!?::bool obj::obj) ((@ isa? __object) obj (@ vset! ast_node)))
(define (vset!-nil::vset!) (class-nil (@ vset! ast_node)))
(define-inline (vset!-vtype::type o::vset!) (-> |#!bigloo_wallow| o vtype))
(define-inline (vset!-vtype-set! o::vset! v::type) (set! (-> |#!bigloo_wallow| o vtype) v))
(define-inline (vset!-otype::type o::vset!) (-> |#!bigloo_wallow| o otype))
(define-inline (vset!-otype-set! o::vset! v::type) (set! (-> |#!bigloo_wallow| o otype) v))
(define-inline (vset!-ftype::type o::vset!) (-> |#!bigloo_wallow| o ftype))
(define-inline (vset!-ftype-set! o::vset! v::type) (set! (-> |#!bigloo_wallow| o ftype) v))
(define-inline (vset!-c-format::bstring o::vset!) (-> |#!bigloo_wallow| o c-format))
(define-inline (vset!-c-format-set! o::vset! v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (vset!-effect::obj o::vset!) (-> |#!bigloo_wallow| o effect))
(define-inline (vset!-effect-set! o::vset! v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (vset!-expr*::pair-nil o::vset!) (-> |#!bigloo_wallow| o expr*))
(define-inline (vset!-expr*-set! o::vset! v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (vset!-key::obj o::vset!) (-> |#!bigloo_wallow| o key))
(define-inline (vset!-key-set! o::vset! v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (vset!-side-effect?::obj o::vset!) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (vset!-side-effect?-set! o::vset! v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (vset!-type::type o::vset!) (-> |#!bigloo_wallow| o type))
(define-inline (vset!-type-set! o::vset! v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (vset!-loc::obj o::vset!) (-> |#!bigloo_wallow| o loc))
(define-inline (vset!-loc-set! o::vset! v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; vlength
(define-inline (make-vlength::vlength loc1445::obj type1446::type side-effect?1447::obj key1448::obj expr*1449::pair-nil effect1450::obj c-format1451::bstring vtype1452::type) (instantiate::vlength (loc loc1445) (type type1446) (side-effect? side-effect?1447) (key key1448) (expr* expr*1449) (effect effect1450) (c-format c-format1451) (vtype vtype1452)))
(define-inline (vlength?::bool obj::obj) ((@ isa? __object) obj (@ vlength ast_node)))
(define (vlength-nil::vlength) (class-nil (@ vlength ast_node)))
(define-inline (vlength-vtype::type o::vlength) (-> |#!bigloo_wallow| o vtype))
(define-inline (vlength-vtype-set! o::vlength v::type) (set! (-> |#!bigloo_wallow| o vtype) v))
(define-inline (vlength-c-format::bstring o::vlength) (-> |#!bigloo_wallow| o c-format))
(define-inline (vlength-c-format-set! o::vlength v::bstring) (set! (-> |#!bigloo_wallow| o c-format) v))
(define-inline (vlength-effect::obj o::vlength) (-> |#!bigloo_wallow| o effect))
(define-inline (vlength-effect-set! o::vlength v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (vlength-expr*::pair-nil o::vlength) (-> |#!bigloo_wallow| o expr*))
(define-inline (vlength-expr*-set! o::vlength v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (vlength-key::obj o::vlength) (-> |#!bigloo_wallow| o key))
(define-inline (vlength-key-set! o::vlength v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (vlength-side-effect?::obj o::vlength) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (vlength-side-effect?-set! o::vlength v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (vlength-type::type o::vlength) (-> |#!bigloo_wallow| o type))
(define-inline (vlength-type-set! o::vlength v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (vlength-loc::obj o::vlength) (-> |#!bigloo_wallow| o loc))
(define-inline (vlength-loc-set! o::vlength v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; isa
(define-inline (make-isa::isa loc1437::obj type1438::type side-effect?1439::obj key1440::obj expr*1441::pair-nil effect1442::obj class1443::type) (instantiate::isa (loc loc1437) (type type1438) (side-effect? side-effect?1439) (key key1440) (expr* expr*1441) (effect effect1442) (class class1443)))
(define-inline (isa?::bool obj::obj) ((@ isa? __object) obj (@ isa ast_node)))
(define (isa-nil::isa) (class-nil (@ isa ast_node)))
(define-inline (isa-class::type o::isa) (-> |#!bigloo_wallow| o class))
(define-inline (isa-class-set! o::isa v::type) (set! (-> |#!bigloo_wallow| o class) v))
(define-inline (isa-effect::obj o::isa) (-> |#!bigloo_wallow| o effect))
(define-inline (isa-effect-set! o::isa v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (isa-expr*::pair-nil o::isa) (-> |#!bigloo_wallow| o expr*))
(define-inline (isa-expr*-set! o::isa v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (isa-key::obj o::isa) (-> |#!bigloo_wallow| o key))
(define-inline (isa-key-set! o::isa v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (isa-side-effect?::obj o::isa) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (isa-side-effect?-set! o::isa v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (isa-type::type o::isa) (-> |#!bigloo_wallow| o type))
(define-inline (isa-type-set! o::isa v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (isa-loc::obj o::isa) (-> |#!bigloo_wallow| o loc))
(define-inline (isa-loc-set! o::isa v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; cast-null
(define-inline (make-cast-null::cast-null loc1430::obj type1431::type side-effect?1432::obj key1433::obj expr*1434::pair-nil effect1435::obj) (instantiate::cast-null (loc loc1430) (type type1431) (side-effect? side-effect?1432) (key key1433) (expr* expr*1434) (effect effect1435)))
(define-inline (cast-null?::bool obj::obj) ((@ isa? __object) obj (@ cast-null ast_node)))
(define (cast-null-nil::cast-null) (class-nil (@ cast-null ast_node)))
(define-inline (cast-null-effect::obj o::cast-null) (-> |#!bigloo_wallow| o effect))
(define-inline (cast-null-effect-set! o::cast-null v::obj) (set! (-> |#!bigloo_wallow| o effect) v))
(define-inline (cast-null-expr*::pair-nil o::cast-null) (-> |#!bigloo_wallow| o expr*))
(define-inline (cast-null-expr*-set! o::cast-null v::pair-nil) (set! (-> |#!bigloo_wallow| o expr*) v))
(define-inline (cast-null-key::obj o::cast-null) (-> |#!bigloo_wallow| o key))
(define-inline (cast-null-key-set! o::cast-null v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (cast-null-side-effect?::obj o::cast-null) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (cast-null-side-effect?-set! o::cast-null v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (cast-null-type::type o::cast-null) (-> |#!bigloo_wallow| o type))
(define-inline (cast-null-type-set! o::cast-null v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (cast-null-loc::obj o::cast-null) (-> |#!bigloo_wallow| o loc))
(define-inline (cast-null-loc-set! o::cast-null v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; cast
(define-inline (make-cast::cast loc1425::obj type1426::type arg1428::node) (instantiate::cast (loc loc1425) (type type1426) (arg arg1428)))
(define-inline (cast?::bool obj::obj) ((@ isa? __object) obj (@ cast ast_node)))
(define (cast-nil::cast) (class-nil (@ cast ast_node)))
(define-inline (cast-arg::node o::cast) (-> |#!bigloo_wallow| o arg))
(define-inline (cast-arg-set! o::cast v::node) (set! (-> |#!bigloo_wallow| o arg) v))
(define-inline (cast-type::type o::cast) (-> |#!bigloo_wallow| o type))
(define-inline (cast-type-set! o::cast v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (cast-loc::obj o::cast) (-> |#!bigloo_wallow| o loc))
(define-inline (cast-loc-set! o::cast v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; setq
(define-inline (make-setq::setq loc1420::obj type1421::type var1422::var value1423::node) (instantiate::setq (loc loc1420) (type type1421) (var var1422) (value value1423)))
(define-inline (setq?::bool obj::obj) ((@ isa? __object) obj (@ setq ast_node)))
(define (setq-nil::setq) (class-nil (@ setq ast_node)))
(define-inline (setq-value::node o::setq) (-> |#!bigloo_wallow| o value))
(define-inline (setq-value-set! o::setq v::node) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (setq-var::var o::setq) (-> |#!bigloo_wallow| o var))
(define-inline (setq-var-set! o::setq v::var) (set! (-> |#!bigloo_wallow| o var) v))
(define-inline (setq-type::type o::setq) (-> |#!bigloo_wallow| o type))
(define-inline (setq-type-set! o::setq v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (setq-loc::obj o::setq) (-> |#!bigloo_wallow| o loc))
(define-inline (setq-loc-set! o::setq v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; conditional
(define-inline (make-conditional::conditional loc1411::obj type1412::type side-effect?1413::obj key1414::obj test1415::node true1416::node false1417::node) (instantiate::conditional (loc loc1411) (type type1412) (side-effect? side-effect?1413) (key key1414) (test test1415) (true true1416) (false false1417)))
(define-inline (conditional?::bool obj::obj) ((@ isa? __object) obj (@ conditional ast_node)))
(define (conditional-nil::conditional) (class-nil (@ conditional ast_node)))
(define-inline (conditional-false::node o::conditional) (-> |#!bigloo_wallow| o false))
(define-inline (conditional-false-set! o::conditional v::node) (set! (-> |#!bigloo_wallow| o false) v))
(define-inline (conditional-true::node o::conditional) (-> |#!bigloo_wallow| o true))
(define-inline (conditional-true-set! o::conditional v::node) (set! (-> |#!bigloo_wallow| o true) v))
(define-inline (conditional-test::node o::conditional) (-> |#!bigloo_wallow| o test))
(define-inline (conditional-test-set! o::conditional v::node) (set! (-> |#!bigloo_wallow| o test) v))
(define-inline (conditional-key::obj o::conditional) (-> |#!bigloo_wallow| o key))
(define-inline (conditional-key-set! o::conditional v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (conditional-side-effect?::obj o::conditional) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (conditional-side-effect?-set! o::conditional v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (conditional-type::type o::conditional) (-> |#!bigloo_wallow| o type))
(define-inline (conditional-type-set! o::conditional v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (conditional-loc::obj o::conditional) (-> |#!bigloo_wallow| o loc))
(define-inline (conditional-loc-set! o::conditional v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; fail
(define-inline (make-fail::fail loc1405::obj type1406::type proc1407::node msg1408::node obj1409::node) (instantiate::fail (loc loc1405) (type type1406) (proc proc1407) (msg msg1408) (obj obj1409)))
(define-inline (fail?::bool obj::obj) ((@ isa? __object) obj (@ fail ast_node)))
(define (fail-nil::fail) (class-nil (@ fail ast_node)))
(define-inline (fail-obj::node o::fail) (-> |#!bigloo_wallow| o obj))
(define-inline (fail-obj-set! o::fail v::node) (set! (-> |#!bigloo_wallow| o obj) v))
(define-inline (fail-msg::node o::fail) (-> |#!bigloo_wallow| o msg))
(define-inline (fail-msg-set! o::fail v::node) (set! (-> |#!bigloo_wallow| o msg) v))
(define-inline (fail-proc::node o::fail) (-> |#!bigloo_wallow| o proc))
(define-inline (fail-proc-set! o::fail v::node) (set! (-> |#!bigloo_wallow| o proc) v))
(define-inline (fail-type::type o::fail) (-> |#!bigloo_wallow| o type))
(define-inline (fail-type-set! o::fail v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (fail-loc::obj o::fail) (-> |#!bigloo_wallow| o loc))
(define-inline (fail-loc-set! o::fail v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; select
(define-inline (make-select::select loc1395::obj type1396::type side-effect?1397::obj key1398::obj test1401::node clauses1402::obj item-type1403::type) (instantiate::select (loc loc1395) (type type1396) (side-effect? side-effect?1397) (key key1398) (test test1401) (clauses clauses1402) (item-type item-type1403)))
(define-inline (select?::bool obj::obj) ((@ isa? __object) obj (@ select ast_node)))
(define (select-nil::select) (class-nil (@ select ast_node)))
(define-inline (select-item-type::type o::select) (-> |#!bigloo_wallow| o item-type))
(define-inline (select-item-type-set! o::select v::type) (set! (-> |#!bigloo_wallow| o item-type) v))
(define-inline (select-clauses::obj o::select) (-> |#!bigloo_wallow| o clauses))
(define-inline (select-clauses-set! o::select v::obj) (set! (-> |#!bigloo_wallow| o clauses) v))
(define-inline (select-test::node o::select) (-> |#!bigloo_wallow| o test))
(define-inline (select-test-set! o::select v::node) (set! (-> |#!bigloo_wallow| o test) v))
(define-inline (select-key::obj o::select) (-> |#!bigloo_wallow| o key))
(define-inline (select-key-set! o::select v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (select-side-effect?::obj o::select) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (select-side-effect?-set! o::select v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (select-type::type o::select) (-> |#!bigloo_wallow| o type))
(define-inline (select-type-set! o::select v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (select-loc::obj o::select) (-> |#!bigloo_wallow| o loc))
(define-inline (select-loc-set! o::select v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; let-fun
(define-inline (make-let-fun::let-fun loc1388::obj type1389::type side-effect?1390::obj key1391::obj locals1392::obj body1393::node) (instantiate::let-fun (loc loc1388) (type type1389) (side-effect? side-effect?1390) (key key1391) (locals locals1392) (body body1393)))
(define-inline (let-fun?::bool obj::obj) ((@ isa? __object) obj (@ let-fun ast_node)))
(define (let-fun-nil::let-fun) (class-nil (@ let-fun ast_node)))
(define-inline (let-fun-body::node o::let-fun) (-> |#!bigloo_wallow| o body))
(define-inline (let-fun-body-set! o::let-fun v::node) (set! (-> |#!bigloo_wallow| o body) v))
(define-inline (let-fun-locals::obj o::let-fun) (-> |#!bigloo_wallow| o locals))
(define-inline (let-fun-locals-set! o::let-fun v::obj) (set! (-> |#!bigloo_wallow| o locals) v))
(define-inline (let-fun-key::obj o::let-fun) (-> |#!bigloo_wallow| o key))
(define-inline (let-fun-key-set! o::let-fun v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (let-fun-side-effect?::obj o::let-fun) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (let-fun-side-effect?-set! o::let-fun v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (let-fun-type::type o::let-fun) (-> |#!bigloo_wallow| o type))
(define-inline (let-fun-type-set! o::let-fun v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (let-fun-loc::obj o::let-fun) (-> |#!bigloo_wallow| o loc))
(define-inline (let-fun-loc-set! o::let-fun v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; let-var
(define-inline (make-let-var::let-var loc1380::obj type1381::type side-effect?1382::obj key1383::obj bindings1384::obj body1385::node removable?1386::bool) (instantiate::let-var (loc loc1380) (type type1381) (side-effect? side-effect?1382) (key key1383) (bindings bindings1384) (body body1385) (removable? removable?1386)))
(define-inline (let-var?::bool obj::obj) ((@ isa? __object) obj (@ let-var ast_node)))
(define (let-var-nil::let-var) (class-nil (@ let-var ast_node)))
(define-inline (let-var-removable?::bool o::let-var) (-> |#!bigloo_wallow| o removable?))
(define-inline (let-var-removable?-set! o::let-var v::bool) (set! (-> |#!bigloo_wallow| o removable?) v))
(define-inline (let-var-body::node o::let-var) (-> |#!bigloo_wallow| o body))
(define-inline (let-var-body-set! o::let-var v::node) (set! (-> |#!bigloo_wallow| o body) v))
(define-inline (let-var-bindings::obj o::let-var) (-> |#!bigloo_wallow| o bindings))
(define-inline (let-var-bindings-set! o::let-var v::obj) (set! (-> |#!bigloo_wallow| o bindings) v))
(define-inline (let-var-key::obj o::let-var) (-> |#!bigloo_wallow| o key))
(define-inline (let-var-key-set! o::let-var v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (let-var-side-effect?::obj o::let-var) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (let-var-side-effect?-set! o::let-var v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (let-var-type::type o::let-var) (-> |#!bigloo_wallow| o type))
(define-inline (let-var-type-set! o::let-var v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (let-var-loc::obj o::let-var) (-> |#!bigloo_wallow| o loc))
(define-inline (let-var-loc-set! o::let-var v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; set-ex-it
(define-inline (make-set-ex-it::set-ex-it loc1375::obj type1376::type var1377::var body1378::node) (instantiate::set-ex-it (loc loc1375) (type type1376) (var var1377) (body body1378)))
(define-inline (set-ex-it?::bool obj::obj) ((@ isa? __object) obj (@ set-ex-it ast_node)))
(define (set-ex-it-nil::set-ex-it) (class-nil (@ set-ex-it ast_node)))
(define-inline (set-ex-it-body::node o::set-ex-it) (-> |#!bigloo_wallow| o body))
(define-inline (set-ex-it-body-set! o::set-ex-it v::node) (set! (-> |#!bigloo_wallow| o body) v))
(define-inline (set-ex-it-var::var o::set-ex-it) (-> |#!bigloo_wallow| o var))
(define-inline (set-ex-it-var-set! o::set-ex-it v::var) (set! (-> |#!bigloo_wallow| o var) v))
(define-inline (set-ex-it-type::type o::set-ex-it) (-> |#!bigloo_wallow| o type))
(define-inline (set-ex-it-type-set! o::set-ex-it v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (set-ex-it-loc::obj o::set-ex-it) (-> |#!bigloo_wallow| o loc))
(define-inline (set-ex-it-loc-set! o::set-ex-it v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; jump-ex-it
(define-inline (make-jump-ex-it::jump-ex-it loc1370::obj type1371::type exit1372::node value1373::node) (instantiate::jump-ex-it (loc loc1370) (type type1371) (exit exit1372) (value value1373)))
(define-inline (jump-ex-it?::bool obj::obj) ((@ isa? __object) obj (@ jump-ex-it ast_node)))
(define (jump-ex-it-nil::jump-ex-it) (class-nil (@ jump-ex-it ast_node)))
(define-inline (jump-ex-it-value::node o::jump-ex-it) (-> |#!bigloo_wallow| o value))
(define-inline (jump-ex-it-value-set! o::jump-ex-it v::node) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (jump-ex-it-exit::node o::jump-ex-it) (-> |#!bigloo_wallow| o exit))
(define-inline (jump-ex-it-exit-set! o::jump-ex-it v::node) (set! (-> |#!bigloo_wallow| o exit) v))
(define-inline (jump-ex-it-type::type o::jump-ex-it) (-> |#!bigloo_wallow| o type))
(define-inline (jump-ex-it-type-set! o::jump-ex-it v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (jump-ex-it-loc::obj o::jump-ex-it) (-> |#!bigloo_wallow| o loc))
(define-inline (jump-ex-it-loc-set! o::jump-ex-it v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; make-box
(define-inline (make-make-box::make-box loc1364::obj type1365::type side-effect?1366::obj key1367::obj value1368::node) (instantiate::make-box (loc loc1364) (type type1365) (side-effect? side-effect?1366) (key key1367) (value value1368)))
(define-inline (make-box?::bool obj::obj) ((@ isa? __object) obj (@ make-box ast_node)))
(define (make-box-nil::make-box) (class-nil (@ make-box ast_node)))
(define-inline (make-box-value::node o::make-box) (-> |#!bigloo_wallow| o value))
(define-inline (make-box-value-set! o::make-box v::node) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (make-box-key::obj o::make-box) (-> |#!bigloo_wallow| o key))
(define-inline (make-box-key-set! o::make-box v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (make-box-side-effect?::obj o::make-box) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (make-box-side-effect?-set! o::make-box v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (make-box-type::type o::make-box) (-> |#!bigloo_wallow| o type))
(define-inline (make-box-type-set! o::make-box v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (make-box-loc::obj o::make-box) (-> |#!bigloo_wallow| o loc))
(define-inline (make-box-loc-set! o::make-box v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; box-ref
(define-inline (make-box-ref::box-ref loc1358::obj type1359::type side-effect?1360::obj key1361::obj var1362::var) (instantiate::box-ref (loc loc1358) (type type1359) (side-effect? side-effect?1360) (key key1361) (var var1362)))
(define-inline (box-ref?::bool obj::obj) ((@ isa? __object) obj (@ box-ref ast_node)))
(define (box-ref-nil::box-ref) (class-nil (@ box-ref ast_node)))
(define-inline (box-ref-var::var o::box-ref) (-> |#!bigloo_wallow| o var))
(define-inline (box-ref-var-set! o::box-ref v::var) (set! (-> |#!bigloo_wallow| o var) v))
(define-inline (box-ref-key::obj o::box-ref) (-> |#!bigloo_wallow| o key))
(define-inline (box-ref-key-set! o::box-ref v::obj) (set! (-> |#!bigloo_wallow| o key) v))
(define-inline (box-ref-side-effect?::obj o::box-ref) (-> |#!bigloo_wallow| o side-effect?))
(define-inline (box-ref-side-effect?-set! o::box-ref v::obj) (set! (-> |#!bigloo_wallow| o side-effect?) v))
(define-inline (box-ref-type::type o::box-ref) (-> |#!bigloo_wallow| o type))
(define-inline (box-ref-type-set! o::box-ref v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (box-ref-loc::obj o::box-ref) (-> |#!bigloo_wallow| o loc))
(define-inline (box-ref-loc-set! o::box-ref v::obj) (set! (-> |#!bigloo_wallow| o loc) v))

;; box-set!
(define-inline (make-box-set!::box-set! loc1353::obj type1354::type var1355::var value1356::node) (instantiate::box-set! (loc loc1353) (type type1354) (var var1355) (value value1356)))
(define-inline (box-set!?::bool obj::obj) ((@ isa? __object) obj (@ box-set! ast_node)))
(define (box-set!-nil::box-set!) (class-nil (@ box-set! ast_node)))
(define-inline (box-set!-value::node o::box-set!) (-> |#!bigloo_wallow| o value))
(define-inline (box-set!-value-set! o::box-set! v::node) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (box-set!-var::var o::box-set!) (-> |#!bigloo_wallow| o var))
(define-inline (box-set!-var-set! o::box-set! v::var) (set! (-> |#!bigloo_wallow| o var) v))
(define-inline (box-set!-type::type o::box-set!) (-> |#!bigloo_wallow| o type))
(define-inline (box-set!-type-set! o::box-set! v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (box-set!-loc::obj o::box-set!) (-> |#!bigloo_wallow| o loc))
(define-inline (box-set!-loc-set! o::box-set! v::obj) (set! (-> |#!bigloo_wallow| o loc) v))
))
