;; ==========================================================
;; Class accessors
;; Bigloo (4.7a)
;; Inria -- Sophia Antipolis     Thu Mar 6 07:34:14 AM CET 2025 
;; (bigloo -classgen Cfa/specialize.scm)
;; ==========================================================

;; The directives
(directives

;; specialized-global
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (static
    (inline make-specialized-global::specialized-global id1121::symbol name1122::obj type1123::type value1124::value access1125::obj fast-alpha1126::obj removable1127::obj occurrence1128::long module1129::symbol import1130::obj evaluable?1131::bool library?1132::bool user?1133::bool pragma1134::obj src1135::obj jvm-type-name1136::bstring fix1137::obj)
    (inline specialized-global?::bool ::obj)
    (specialized-global-nil::specialized-global)
    (inline specialized-global-fix::obj ::specialized-global)
    (inline specialized-global-jvm-type-name::bstring ::specialized-global)
    (inline specialized-global-jvm-type-name-set! ::specialized-global ::bstring)
    (inline specialized-global-src::obj ::specialized-global)
    (inline specialized-global-src-set! ::specialized-global ::obj)
    (inline specialized-global-pragma::obj ::specialized-global)
    (inline specialized-global-pragma-set! ::specialized-global ::obj)
    (inline specialized-global-user?::bool ::specialized-global)
    (inline specialized-global-user?-set! ::specialized-global ::bool)
    (inline specialized-global-library?::bool ::specialized-global)
    (inline specialized-global-library?-set! ::specialized-global ::bool)
    (inline specialized-global-evaluable?::bool ::specialized-global)
    (inline specialized-global-evaluable?-set! ::specialized-global ::bool)
    (inline specialized-global-import::obj ::specialized-global)
    (inline specialized-global-import-set! ::specialized-global ::obj)
    (inline specialized-global-module::symbol ::specialized-global)
    (inline specialized-global-module-set! ::specialized-global ::symbol)
    (inline specialized-global-occurrence::long ::specialized-global)
    (inline specialized-global-occurrence-set! ::specialized-global ::long)
    (inline specialized-global-removable::obj ::specialized-global)
    (inline specialized-global-removable-set! ::specialized-global ::obj)
    (inline specialized-global-fast-alpha::obj ::specialized-global)
    (inline specialized-global-fast-alpha-set! ::specialized-global ::obj)
    (inline specialized-global-access::obj ::specialized-global)
    (inline specialized-global-access-set! ::specialized-global ::obj)
    (inline specialized-global-value::value ::specialized-global)
    (inline specialized-global-value-set! ::specialized-global ::value)
    (inline specialized-global-type::type ::specialized-global)
    (inline specialized-global-type-set! ::specialized-global ::type)
    (inline specialized-global-name::obj ::specialized-global)
    (inline specialized-global-name-set! ::specialized-global ::obj)
    (inline specialized-global-id::symbol ::specialized-global)))))

;; The definitions
(cond-expand (bigloo-class-sans
;; specialized-global
(define-inline (make-specialized-global::specialized-global id1121::symbol name1122::obj type1123::type value1124::value access1125::obj fast-alpha1126::obj removable1127::obj occurrence1128::long module1129::symbol import1130::obj evaluable?1131::bool library?1132::bool user?1133::bool pragma1134::obj src1135::obj jvm-type-name1136::bstring fix1137::obj) (instantiate::specialized-global (id id1121) (name name1122) (type type1123) (value value1124) (access access1125) (fast-alpha fast-alpha1126) (removable removable1127) (occurrence occurrence1128) (module module1129) (import import1130) (evaluable? evaluable?1131) (library? library?1132) (user? user?1133) (pragma pragma1134) (src src1135) (jvm-type-name jvm-type-name1136) (fix fix1137)))
(define-inline (specialized-global?::bool obj::obj) ((@ isa? __object) obj (@ specialized-global cfa_specialize)))
(define (specialized-global-nil::specialized-global) (class-nil (@ specialized-global cfa_specialize)))
(define-inline (specialized-global-fix::obj o::specialized-global) (-> |#!bigloo_wallow| o fix))
(define-inline (specialized-global-fix-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o fix) v))
(define-inline (specialized-global-jvm-type-name::bstring o::specialized-global) (-> |#!bigloo_wallow| o jvm-type-name))
(define-inline (specialized-global-jvm-type-name-set! o::specialized-global v::bstring) (set! (-> |#!bigloo_wallow| o jvm-type-name) v))
(define-inline (specialized-global-src::obj o::specialized-global) (-> |#!bigloo_wallow| o src))
(define-inline (specialized-global-src-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o src) v))
(define-inline (specialized-global-pragma::obj o::specialized-global) (-> |#!bigloo_wallow| o pragma))
(define-inline (specialized-global-pragma-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o pragma) v))
(define-inline (specialized-global-user?::bool o::specialized-global) (-> |#!bigloo_wallow| o user?))
(define-inline (specialized-global-user?-set! o::specialized-global v::bool) (set! (-> |#!bigloo_wallow| o user?) v))
(define-inline (specialized-global-library?::bool o::specialized-global) (-> |#!bigloo_wallow| o library?))
(define-inline (specialized-global-library?-set! o::specialized-global v::bool) (set! (-> |#!bigloo_wallow| o library?) v))
(define-inline (specialized-global-evaluable?::bool o::specialized-global) (-> |#!bigloo_wallow| o evaluable?))
(define-inline (specialized-global-evaluable?-set! o::specialized-global v::bool) (set! (-> |#!bigloo_wallow| o evaluable?) v))
(define-inline (specialized-global-import::obj o::specialized-global) (-> |#!bigloo_wallow| o import))
(define-inline (specialized-global-import-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o import) v))
(define-inline (specialized-global-module::symbol o::specialized-global) (-> |#!bigloo_wallow| o module))
(define-inline (specialized-global-module-set! o::specialized-global v::symbol) (set! (-> |#!bigloo_wallow| o module) v))
(define-inline (specialized-global-occurrence::long o::specialized-global) (-> |#!bigloo_wallow| o occurrence))
(define-inline (specialized-global-occurrence-set! o::specialized-global v::long) (set! (-> |#!bigloo_wallow| o occurrence) v))
(define-inline (specialized-global-removable::obj o::specialized-global) (-> |#!bigloo_wallow| o removable))
(define-inline (specialized-global-removable-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o removable) v))
(define-inline (specialized-global-fast-alpha::obj o::specialized-global) (-> |#!bigloo_wallow| o fast-alpha))
(define-inline (specialized-global-fast-alpha-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o fast-alpha) v))
(define-inline (specialized-global-access::obj o::specialized-global) (-> |#!bigloo_wallow| o access))
(define-inline (specialized-global-access-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o access) v))
(define-inline (specialized-global-value::value o::specialized-global) (-> |#!bigloo_wallow| o value))
(define-inline (specialized-global-value-set! o::specialized-global v::value) (set! (-> |#!bigloo_wallow| o value) v))
(define-inline (specialized-global-type::type o::specialized-global) (-> |#!bigloo_wallow| o type))
(define-inline (specialized-global-type-set! o::specialized-global v::type) (set! (-> |#!bigloo_wallow| o type) v))
(define-inline (specialized-global-name::obj o::specialized-global) (-> |#!bigloo_wallow| o name))
(define-inline (specialized-global-name-set! o::specialized-global v::obj) (set! (-> |#!bigloo_wallow| o name) v))
(define-inline (specialized-global-id::symbol o::specialized-global) (-> |#!bigloo_wallow| o id))
(define-inline (specialized-global-id-set! o::specialized-global v::symbol) (set! (-> |#!bigloo_wallow| o id) v))
))
