;; ==========================================================
;; Class accessors
;; Bigloo (3.8a)
;; Inria -- Sophia Antipolis     Wed Mar 14 07:20:00 CET 2012 
;; (bigloo barchart.scm -classgen)
;; ==========================================================

;; The directives
(directives

;; chart
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (static
    (inline make-chart::chart legend1063::bstring bar-width1064::obj sep-width1065::obj hline1066::int hline-start1067::obj hline-increment1068::obj hline-fixnum?1069::bool secondary-hline1070::obj actual-max1071::obj request-max1072::obj nb-bars1073::int bars1074::pair-nil suffix1075::obj write-values1076::obj)
    (inline chart?::bool ::obj)
    (chart-nil::chart)
    (inline chart-write-values::obj ::chart)
    (inline chart-write-values-set! ::chart ::obj)
    (inline chart-suffix::obj ::chart)
    (inline chart-suffix-set! ::chart ::obj)
    (inline chart-bars::pair-nil ::chart)
    (inline chart-bars-set! ::chart ::pair-nil)
    (inline chart-nb-bars::int ::chart)
    (inline chart-nb-bars-set! ::chart ::int)
    (inline chart-request-max::obj ::chart)
    (inline chart-request-max-set! ::chart ::obj)
    (inline chart-actual-max::obj ::chart)
    (inline chart-actual-max-set! ::chart ::obj)
    (inline chart-secondary-hline::obj ::chart)
    (inline chart-secondary-hline-set! ::chart ::obj)
    (inline chart-hline-fixnum?::bool ::chart)
    (inline chart-hline-fixnum?-set! ::chart ::bool)
    (inline chart-hline-increment::obj ::chart)
    (inline chart-hline-increment-set! ::chart ::obj)
    (inline chart-hline-start::obj ::chart)
    (inline chart-hline-start-set! ::chart ::obj)
    (inline chart-hline::int ::chart)
    (inline chart-hline-set! ::chart ::int)
    (inline chart-sep-width::obj ::chart)
    (inline chart-sep-width-set! ::chart ::obj)
    (inline chart-bar-width::obj ::chart)
    (inline chart-bar-width-set! ::chart ::obj)
    (inline chart-legend::bstring ::chart)
    (inline chart-legend-set! ::chart ::bstring)))))

;; The definitions
(cond-expand (bigloo-class-sans
;; chart
(define-inline (make-chart::chart legend1063::bstring bar-width1064::obj sep-width1065::obj hline1066::int hline-start1067::obj hline-increment1068::obj hline-fixnum?1069::bool secondary-hline1070::obj actual-max1071::obj request-max1072::obj nb-bars1073::int bars1074::pair-nil suffix1075::obj write-values1076::obj) (instantiate::chart (legend legend1063) (bar-width bar-width1064) (sep-width sep-width1065) (hline hline1066) (hline-start hline-start1067) (hline-increment hline-increment1068) (hline-fixnum? hline-fixnum?1069) (secondary-hline secondary-hline1070) (actual-max actual-max1071) (request-max request-max1072) (nb-bars nb-bars1073) (bars bars1074) (suffix suffix1075) (write-values write-values1076)))
(define-inline (chart?::bool obj::obj) ((@ isa? __object) obj (@ chart barchart)))
(define (chart-nil::chart) (class-nil (@ chart barchart)))
(define-inline (chart-write-values::obj o::chart) (with-access::chart o (write-values) write-values))
(define-inline (chart-write-values-set! o::chart v::obj) (with-access::chart o (write-values) (set! write-values v)))
(define-inline (chart-suffix::obj o::chart) (with-access::chart o (suffix) suffix))
(define-inline (chart-suffix-set! o::chart v::obj) (with-access::chart o (suffix) (set! suffix v)))
(define-inline (chart-bars::pair-nil o::chart) (with-access::chart o (bars) bars))
(define-inline (chart-bars-set! o::chart v::pair-nil) (with-access::chart o (bars) (set! bars v)))
(define-inline (chart-nb-bars::int o::chart) (with-access::chart o (nb-bars) nb-bars))
(define-inline (chart-nb-bars-set! o::chart v::int) (with-access::chart o (nb-bars) (set! nb-bars v)))
(define-inline (chart-request-max::obj o::chart) (with-access::chart o (request-max) request-max))
(define-inline (chart-request-max-set! o::chart v::obj) (with-access::chart o (request-max) (set! request-max v)))
(define-inline (chart-actual-max::obj o::chart) (with-access::chart o (actual-max) actual-max))
(define-inline (chart-actual-max-set! o::chart v::obj) (with-access::chart o (actual-max) (set! actual-max v)))
(define-inline (chart-secondary-hline::obj o::chart) (with-access::chart o (secondary-hline) secondary-hline))
(define-inline (chart-secondary-hline-set! o::chart v::obj) (with-access::chart o (secondary-hline) (set! secondary-hline v)))
(define-inline (chart-hline-fixnum?::bool o::chart) (with-access::chart o (hline-fixnum?) hline-fixnum?))
(define-inline (chart-hline-fixnum?-set! o::chart v::bool) (with-access::chart o (hline-fixnum?) (set! hline-fixnum? v)))
(define-inline (chart-hline-increment::obj o::chart) (with-access::chart o (hline-increment) hline-increment))
(define-inline (chart-hline-increment-set! o::chart v::obj) (with-access::chart o (hline-increment) (set! hline-increment v)))
(define-inline (chart-hline-start::obj o::chart) (with-access::chart o (hline-start) hline-start))
(define-inline (chart-hline-start-set! o::chart v::obj) (with-access::chart o (hline-start) (set! hline-start v)))
(define-inline (chart-hline::int o::chart) (with-access::chart o (hline) hline))
(define-inline (chart-hline-set! o::chart v::int) (with-access::chart o (hline) (set! hline v)))
(define-inline (chart-sep-width::obj o::chart) (with-access::chart o (sep-width) sep-width))
(define-inline (chart-sep-width-set! o::chart v::obj) (with-access::chart o (sep-width) (set! sep-width v)))
(define-inline (chart-bar-width::obj o::chart) (with-access::chart o (bar-width) bar-width))
(define-inline (chart-bar-width-set! o::chart v::obj) (with-access::chart o (bar-width) (set! bar-width v)))
(define-inline (chart-legend::bstring o::chart) (with-access::chart o (legend) legend))
(define-inline (chart-legend-set! o::chart v::bstring) (with-access::chart o (legend) (set! legend v)))
))
