include ../../../Makefile.config
include Makefile.objects

OCAML=ocamlopt
FLAGS=-unsafe -O3 $(OCAMLFLAGS)

compile: ocaml.exe

ocaml.exe: $(OBJECTS)
	$(OCAML) $(FLAGS) $(OBJECTS:%.o=%.cmx) -o $@

clean:
	-@/bin/rm -f ocaml.exe 2> /dev/null
	-@/bin/rm -rf $(OBJECTS) 2> /dev/null
	-@/bin/rm -rf *.cm* 2> /dev/null


.SUFFIXES:
.SUFFIXES: .ml .o

.ml.o:
	$(OCAML) $(FLAGS) $*.ml -o $*.o -c

