;; ==========================================================
;; Class accessors
;; Bigloo (3.8a)
;; Inria -- Sophia Antipolis     Wed Mar 14 07:20:00 CET 2012 
;; (bigloo Arch/arch.scm -classgen)
;; ==========================================================

;; The directives
(directives

;; target-info
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate))
  (static
    (inline make-target-info::target-info word-size1138::int sp-expr1139::ir-expr fp-expr1140::ir-expr old-fp1141::obj retv-expr1142::ir-expr reta-expr1143::ir-expr zero-expr1144::ir-expr nop-expr1145::obj arg-registers1146::obj caller-save-register1147::obj callee-save-register1148::obj calldef-registers1149::obj calluse-registers1150::obj bss-expr1151::ir-expr iselect1152::procedure save-register1153::procedure restore-register1154::procedure enlarge-stack1155::procedure shrink-stack1156::procedure stack-grows-down?1157::bool move-registers1158::procedure add-registers1159::procedure text-section1160::obj runtime-code1161::bstring compile-data1162::procedure bss-segment1163::procedure set-gp1164::procedure)
    (inline target-info?::bool ::obj)
    (target-info-nil::target-info)
    (inline target-info-set-gp::procedure ::target-info)
    (inline target-info-bss-segment::procedure ::target-info)
    (inline target-info-compile-data::procedure ::target-info)
    (inline target-info-runtime-code::bstring ::target-info)
    (inline target-info-text-section::obj ::target-info)
    (inline target-info-add-registers::procedure ::target-info)
    (inline target-info-move-registers::procedure ::target-info)
    (inline target-info-stack-grows-down?::bool ::target-info)
    (inline target-info-shrink-stack::procedure ::target-info)
    (inline target-info-enlarge-stack::procedure ::target-info)
    (inline target-info-restore-register::procedure ::target-info)
    (inline target-info-save-register::procedure ::target-info)
    (inline target-info-iselect::procedure ::target-info)
    (inline target-info-bss-expr::ir-expr ::target-info)
    (inline target-info-calluse-registers::obj ::target-info)
    (inline target-info-calldef-registers::obj ::target-info)
    (inline target-info-callee-save-registers::obj ::target-info)
    (inline target-info-caller-save-registers::obj ::target-info)
    (inline target-info-arg-registers::obj ::target-info)
    (inline target-info-nop-expr::obj ::target-info)
    (inline target-info-zero-expr::ir-expr ::target-info)
    (inline target-info-reta-expr::ir-expr ::target-info)
    (inline target-info-retv-expr::ir-expr ::target-info)
    (inline target-info-old-fp::obj ::target-info)
    (inline target-info-fp-expr::ir-expr ::target-info)
    (inline target-info-sp-expr::ir-expr ::target-info)
    (inline target-info-word-size::int ::target-info)))))

;; The definitions
(cond-expand (bigloo-class-sans
;; target-info
(define-inline (make-target-info::target-info word-size1138::int sp-expr1139::ir-expr fp-expr1140::ir-expr old-fp1141::obj retv-expr1142::ir-expr reta-expr1143::ir-expr zero-expr1144::ir-expr nop-expr1145::obj arg-registers1146::obj caller-save-register1147::obj callee-save-register1148::obj calldef-registers1149::obj calluse-registers1150::obj bss-expr1151::ir-expr iselect1152::procedure save-register1153::procedure restore-register1154::procedure enlarge-stack1155::procedure shrink-stack1156::procedure stack-grows-down?1157::bool move-registers1158::procedure add-registers1159::procedure text-section1160::obj runtime-code1161::bstring compile-data1162::procedure bss-segment1163::procedure set-gp1164::procedure) (instantiate::target-info (word-size word-size1138) (sp-expr sp-expr1139) (fp-expr fp-expr1140) (old-fp old-fp1141) (retv-expr retv-expr1142) (reta-expr reta-expr1143) (zero-expr zero-expr1144) (nop-expr nop-expr1145) (arg-registers arg-registers1146) (caller-save-registers caller-save-register1147) (callee-save-registers callee-save-register1148) (calldef-registers calldef-registers1149) (calluse-registers calluse-registers1150) (bss-expr bss-expr1151) (iselect iselect1152) (save-register save-register1153) (restore-register restore-register1154) (enlarge-stack enlarge-stack1155) (shrink-stack shrink-stack1156) (stack-grows-down? stack-grows-down?1157) (move-registers move-registers1158) (add-registers add-registers1159) (text-section text-section1160) (runtime-code runtime-code1161) (compile-data compile-data1162) (bss-segment bss-segment1163) (set-gp set-gp1164)))
(define-inline (target-info?::bool obj::obj) ((@ isa? __object) obj (@ target-info arch_arch)))
(define (target-info-nil::target-info) (class-nil (@ target-info arch_arch)))
(define-inline (target-info-set-gp::procedure o::target-info) (with-access::target-info o (set-gp) set-gp))
(define-inline (target-info-set-gp-set! o::target-info v::procedure) (with-access::target-info o (set-gp) (set! set-gp v)))
(define-inline (target-info-bss-segment::procedure o::target-info) (with-access::target-info o (bss-segment) bss-segment))
(define-inline (target-info-bss-segment-set! o::target-info v::procedure) (with-access::target-info o (bss-segment) (set! bss-segment v)))
(define-inline (target-info-compile-data::procedure o::target-info) (with-access::target-info o (compile-data) compile-data))
(define-inline (target-info-compile-data-set! o::target-info v::procedure) (with-access::target-info o (compile-data) (set! compile-data v)))
(define-inline (target-info-runtime-code::bstring o::target-info) (with-access::target-info o (runtime-code) runtime-code))
(define-inline (target-info-runtime-code-set! o::target-info v::bstring) (with-access::target-info o (runtime-code) (set! runtime-code v)))
(define-inline (target-info-text-section::obj o::target-info) (with-access::target-info o (text-section) text-section))
(define-inline (target-info-text-section-set! o::target-info v::obj) (with-access::target-info o (text-section) (set! text-section v)))
(define-inline (target-info-add-registers::procedure o::target-info) (with-access::target-info o (add-registers) add-registers))
(define-inline (target-info-add-registers-set! o::target-info v::procedure) (with-access::target-info o (add-registers) (set! add-registers v)))
(define-inline (target-info-move-registers::procedure o::target-info) (with-access::target-info o (move-registers) move-registers))
(define-inline (target-info-move-registers-set! o::target-info v::procedure) (with-access::target-info o (move-registers) (set! move-registers v)))
(define-inline (target-info-stack-grows-down?::bool o::target-info) (with-access::target-info o (stack-grows-down?) stack-grows-down?))
(define-inline (target-info-stack-grows-down?-set! o::target-info v::bool) (with-access::target-info o (stack-grows-down?) (set! stack-grows-down? v)))
(define-inline (target-info-shrink-stack::procedure o::target-info) (with-access::target-info o (shrink-stack) shrink-stack))
(define-inline (target-info-shrink-stack-set! o::target-info v::procedure) (with-access::target-info o (shrink-stack) (set! shrink-stack v)))
(define-inline (target-info-enlarge-stack::procedure o::target-info) (with-access::target-info o (enlarge-stack) enlarge-stack))
(define-inline (target-info-enlarge-stack-set! o::target-info v::procedure) (with-access::target-info o (enlarge-stack) (set! enlarge-stack v)))
(define-inline (target-info-restore-register::procedure o::target-info) (with-access::target-info o (restore-register) restore-register))
(define-inline (target-info-restore-register-set! o::target-info v::procedure) (with-access::target-info o (restore-register) (set! restore-register v)))
(define-inline (target-info-save-register::procedure o::target-info) (with-access::target-info o (save-register) save-register))
(define-inline (target-info-save-register-set! o::target-info v::procedure) (with-access::target-info o (save-register) (set! save-register v)))
(define-inline (target-info-iselect::procedure o::target-info) (with-access::target-info o (iselect) iselect))
(define-inline (target-info-iselect-set! o::target-info v::procedure) (with-access::target-info o (iselect) (set! iselect v)))
(define-inline (target-info-bss-expr::ir-expr o::target-info) (with-access::target-info o (bss-expr) bss-expr))
(define-inline (target-info-bss-expr-set! o::target-info v::ir-expr) (with-access::target-info o (bss-expr) (set! bss-expr v)))
(define-inline (target-info-calluse-registers::obj o::target-info) (with-access::target-info o (calluse-registers) calluse-registers))
(define-inline (target-info-calluse-registers-set! o::target-info v::obj) (with-access::target-info o (calluse-registers) (set! calluse-registers v)))
(define-inline (target-info-calldef-registers::obj o::target-info) (with-access::target-info o (calldef-registers) calldef-registers))
(define-inline (target-info-calldef-registers-set! o::target-info v::obj) (with-access::target-info o (calldef-registers) (set! calldef-registers v)))
(define-inline (target-info-callee-save-registers::obj o::target-info) (with-access::target-info o (callee-save-registers) callee-save-registers))
(define-inline (target-info-callee-save-registers-set! o::target-info v::obj) (with-access::target-info o (callee-save-registers) (set! callee-save-registers v)))
(define-inline (target-info-caller-save-registers::obj o::target-info) (with-access::target-info o (caller-save-registers) caller-save-registers))
(define-inline (target-info-caller-save-registers-set! o::target-info v::obj) (with-access::target-info o (caller-save-registers) (set! caller-save-registers v)))
(define-inline (target-info-arg-registers::obj o::target-info) (with-access::target-info o (arg-registers) arg-registers))
(define-inline (target-info-arg-registers-set! o::target-info v::obj) (with-access::target-info o (arg-registers) (set! arg-registers v)))
(define-inline (target-info-nop-expr::obj o::target-info) (with-access::target-info o (nop-expr) nop-expr))
(define-inline (target-info-nop-expr-set! o::target-info v::obj) (with-access::target-info o (nop-expr) (set! nop-expr v)))
(define-inline (target-info-zero-expr::ir-expr o::target-info) (with-access::target-info o (zero-expr) zero-expr))
(define-inline (target-info-zero-expr-set! o::target-info v::ir-expr) (with-access::target-info o (zero-expr) (set! zero-expr v)))
(define-inline (target-info-reta-expr::ir-expr o::target-info) (with-access::target-info o (reta-expr) reta-expr))
(define-inline (target-info-reta-expr-set! o::target-info v::ir-expr) (with-access::target-info o (reta-expr) (set! reta-expr v)))
(define-inline (target-info-retv-expr::ir-expr o::target-info) (with-access::target-info o (retv-expr) retv-expr))
(define-inline (target-info-retv-expr-set! o::target-info v::ir-expr) (with-access::target-info o (retv-expr) (set! retv-expr v)))
(define-inline (target-info-old-fp::obj o::target-info) (with-access::target-info o (old-fp) old-fp))
(define-inline (target-info-old-fp-set! o::target-info v::obj) (with-access::target-info o (old-fp) (set! old-fp v)))
(define-inline (target-info-fp-expr::ir-expr o::target-info) (with-access::target-info o (fp-expr) fp-expr))
(define-inline (target-info-fp-expr-set! o::target-info v::ir-expr) (with-access::target-info o (fp-expr) (set! fp-expr v)))
(define-inline (target-info-sp-expr::ir-expr o::target-info) (with-access::target-info o (sp-expr) sp-expr))
(define-inline (target-info-sp-expr-set! o::target-info v::ir-expr) (with-access::target-info o (sp-expr) (set! sp-expr v)))
(define-inline (target-info-word-size::int o::target-info) (with-access::target-info o (word-size) word-size))
(define-inline (target-info-word-size-set! o::target-info v::int) (with-access::target-info o (word-size) (set! word-size v)))
))
